name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
          java-version: '11'
          distribution: 'temurin'

    - name: Build WAR using Maven
      run: mvn clean package -Dmaven.test.skip=true --file pom.xml
        
    - name: Upload WAR to EC2
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        source: "target/springLegacyProject.war"
        target: "/home/ubuntu/build/"

    - name: Run deploy script
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        script: |
          chmod +x /home/ubuntu/deploy.sh
          /home/ubuntu/deploy.sh
